apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - namespace.yaml
  - configmaps/global-config.yaml
  - deployments/api-gateway-deployment.yaml
  - deployments/user-service-deployment.yaml
  - deployments/product-service-deployment.yaml
  - deployments/order-service-deployment.yaml
  - services/api-gateway-service.yaml
  - services/user-service.yaml
  - services/product-service.yaml
  - services/order-service.yaml
