spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/ecommerce}
    username: ${DB_USERNAME:ecommerce}
    password: ${DB_PASSWORD:ecommerce}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}

