apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-global-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  LOGGING_LEVEL_ROOT: "INFO"
